### ISSUE TITLE
update to  async actions

### ISSUE THREAD

**Issue by Garibaldy** [ajgribble/sails-json-api#28]
**Support asynchronous actions that could take awhile to process (202 Accepted)**

i'm able to 

`localhost:1337/api/v1/users/1`

but not (and the mock doesn't have more than 10 users)

`localhost:1337/api/v1/users`

probably related with #27

**Comment by ajgribble** [comment]
Please provide additional information on this issue (e.g. errors received, expected responses, actions being performed)

**Comment by Garibaldy** [comment]
> Please provide additional information on this issue (e.g. errors received, expected responses, actions being performed)

solved by PR #29
